language: rust
sudo: required
dist: trusty
cache: cargo
addons:
  apt:
    packages:
      - libssl-dev
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
script:
  - cargo clean
  - cargo build 
  - cargo test
